travis:
  secure:
    BINSTAR_TOKEN: D4MT4osk3aYdgShIuorEV8ERZQzsi8i0/YjAA9OWizMivAza25Z6F5Hds1aMUnJBVbLg2fJ2rXwMRk+yMVR3sySNiWdSm7hGDphUe//VJgbABq+j7pxsLbKl1/KvPPNBj9SK7fzgGrN0HH40ASmCDQIMGDOR+eid5536nMlSUupw0cV/YBnWosOq9tihU+jYeaWL7fi+9/YibN9Y+F6v/xKEhtG28Fxc/vOrwn+aJp02yLXpOXgvL8KYfqDRLjyRidoFcEbBoiLCf9luNZBbZ/X1opSEGGaKKszaMW2OO1VxFSh5HTBiZ/gue8g+GFFj+iDmPy0KBmCkzzPF2IHCn0ElScF2yqMRMK3QLa0DHitAi+fLtLqAk7twXuDBwOU0OdRmi4NotWwOG9mTafv2n4QoFseZTuVlm+ZQeN+eE6Gf5yOYl/UEU7diIv8/UKsWdZ6ogaPHpN0JUD+fuPw4bzKqm0XgFdIXAOLncaaQvuTWhwNFWAZqcD1anf4Kh6F3+eVsHLvOCSa0Ro7lwxWAzm2g2GBJJOd0HQCZVBIF77vNyjtc42nWvZVLmhhNRGFqTTz9IBSy1r25seyB1X4Bphp93hPx7ZfRNW7NKSGQj5lV0poFId9VnX84Zg9CAEFvQC/Pzf6thNsMYQ7gOtkq/WHlR2YHnkMQ/1nSfKu3JUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
