travis:
  secure:
    BINSTAR_TOKEN: oaMXxbaOBft0VyK0uXl4luk3HbxqUNScVbl7TauH72ICd/nXvd41go7CoK+eCl2GuOaM0QxckRLGpFvPs3Bl+SV1X5AO4uHRMGL9ArvI88F21QRd5T0/zm+zgz2UDkTqFk0P6mG874LvpoGrXG2jebT3+cPybiA2G83pwhDsgYFPKxmtmw9heTksB+OOXabSlkWzSsFeH/ZKZ3fXk/vObSWw6ybCnksiU1UAqYq9gJ9Z9l26u0fUXk+Ax9hRsJHl8eyqnptEJ0JNezDhBLtjAVdpHyzrt7UEGw/o032m9hQCwUdtYquagTa9slsKEyQlp63u4M8N9FWMJmWIKWdZtmq0vx6uXB42Lq2ZvwgHs+cw5uyw2vhwLTJ6aPSiM/Y5AqsLPuiTaep5rUmP570ze5U7ygUG08KyQQFNwSD+ZKqGZ4c7yhns3EP9UiTc04MkexKetqj4ODIwC1+6oOZcwUWp8rG1ex3SoZ0uduIRzVkbZaNGuCKEiJNJQ/OLpOk3tHtLxZQ5Hj4ZXXPs5j263GdzjRAoohxHTAIUXtwODZn/aYg88ZLyvin/DQdkZ6lk2u2W7HHUX82A0AsR289ZPnn86j7SZQuUYQGwgzDGHfcF97+MS7/8OEKVzwIQsJPtUNyy9bbrbEyhl0jUYCVc0NRSdvsCCT4e5IlFSqT1AFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
